### ISSUE TITLE
v5.0.14 broken on Leia

### ISSUE THREAD

**Issue by ABH10** [xbmc-danish-addons/plugin.video.drnu#50]
The new v5.0.14 doesn't work for me. 
I had to revert to v5.0.13 that works fine, although it says it is marked as broken.
I am using Rpi3B+ with Libreelec 9.2 (Kodi 18.9).
Used the bug reporting feature to send a bug reprot to somewhere :-)

**Comment by TermeHansen** [comment]
Weird, I'm using same setup just with osmc instead of libreelec.
I will see if I have access to the error server of Tommy, elsewhere I guess I have to setup my own and change for that.

But elsewhere can you be more specific on when it crashes and the steps leading to it or maybe share the error part from the error dialog?

**Comment by ABH10** [comment]
First of all, thank you for continuing the work with the app!

I have been digging a little deeper. There seems to be two versions with version number 5.0.13.
This is the status for me:
5.0.13 by MSJ33              is OK
5.0.13 by TermeHansen   is not OK
5.0.14 by TermeHansen   is not OK

Live TV is OK on all versions.

If you start a video, that you have not seen before, then it will play just fine.
If you start a video, that you have seen before (partly or fully), then you will see the error message right away, when you try to start the video again.

So, the problem might be a change to the storage format, where the app keeps the info about already played videos (?)

**Comment by TermeHansen** [comment]
@ABH10 can I get you to try to install the very latest in leia branch (just download the zip, and install in kodi) https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/leia

I have added so the error submittion now should send a mail that I can see.

**Comment by TermeHansen** [comment]
Thanks, I'll try to fix for you to test

**Comment by TermeHansen** [comment]
Still a bit weird that it happens to you on libreelec and not for me here on osmc. Anyhow I know what the problem is and we can solve it, but I would like to see if I can solve en a general matter to use the same code in both leia and matrix. I have made a new branch for our testing. 
Can you please test https://github.com/xbmc-danish-addons/plugin.video.drnu/tree/bug/unicode_open_libreelec

It is only the `resources/lib/tvapi.py` that has the problem, so you can also just copy that file into `/storage/.kodi/addons/plugin.video.drnu/resources/lib/tvapi.py`

**Comment by TermeHansen** [comment]
One more test

**Comment by TermeHansen** [comment]
Thanks. I will install libreelec on my RPi3  now and see if an reproduce to understand the core of this....

**Comment by ABH10** [comment]
It works, if I set Kodi language to English!
I tried to go back to Danish language in Kodi and use another character set than "Default". I tried "Western Europe (ISO)" and "Western Europe (Windows)", but that did not help.
I tried videos that didn't have Danish characters in the "name" but that didn't work either.

**Comment by TermeHansen** [comment]
I can reproduce on libreelec - great - I will solve and let you know...

**Comment by TermeHansen** [comment]
Allright fixed (I think :) ) please try the one from leia branch https://github.com/xbmc-danish-addons/plugin.video.drnu/archive/leia.zip

**Comment by ABH10** [comment]
Seems to work OK now. Thank you.
